projects:
  iot-client:
    schemaPath: app/graphql/schema.json
    includes:
      - app/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/graphql/API.ts
        docsFilePath: app/graphql
        region: ap-northeast-1
        apiId: hwgnjo3cefb6ld2gnmvilv6ddi
        maxDepth: 5
extensions:
  amplify:
    version: 3
